[install]
# Use exact versions for better reproducibility
exact = true

[install.scopes]
# Configure any scoped packages if needed

[test]
# Test configuration

[run]
# Runtime configuration
bun = true

[build]
# Build configuration
target = "bun"
